// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK6vQIH8-jFwqhMWQjlym0bH5lVv56h0I',
    appId: '1:1073627145116:web:1307dbdcfc03878c5fde59',
    messagingSenderId: '1073627145116',
    projectId: 'todo-list-a4fd4',
    authDomain: 'todo-list-a4fd4.firebaseapp.com',
    storageBucket: 'todo-list-a4fd4.firebasestorage.app',
    measurementId: 'G-DKJENT14J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7FxpPNaO1UGGaGTgEh86aM4NHoEzsMRs',
    appId: '1:1073627145116:android:bfcaadb7db7b42ec5fde59',
    messagingSenderId: '1073627145116',
    projectId: 'todo-list-a4fd4',
    storageBucket: 'todo-list-a4fd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6FRhKblFOgkL47yKpCNqnwBZXfU35WEY',
    appId: '1:1073627145116:ios:5642f79def8c2f435fde59',
    messagingSenderId: '1073627145116',
    projectId: 'todo-list-a4fd4',
    storageBucket: 'todo-list-a4fd4.firebasestorage.app',
    iosBundleId: 'com.example.browsekigali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6FRhKblFOgkL47yKpCNqnwBZXfU35WEY',
    appId: '1:1073627145116:ios:5642f79def8c2f435fde59',
    messagingSenderId: '1073627145116',
    projectId: 'todo-list-a4fd4',
    storageBucket: 'todo-list-a4fd4.firebasestorage.app',
    iosBundleId: 'com.example.browsekigali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK6vQIH8-jFwqhMWQjlym0bH5lVv56h0I',
    appId: '1:1073627145116:web:6b7238cd8d64fac55fde59',
    messagingSenderId: '1073627145116',
    projectId: 'todo-list-a4fd4',
    authDomain: 'todo-list-a4fd4.firebaseapp.com',
    storageBucket: 'todo-list-a4fd4.firebasestorage.app',
    measurementId: 'G-PXZNM4SF2E',
  );
}
